name: Generate Snake

on:
  schedule: # Runs at 12am UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v2

      # Generate the snake animation
      - uses: Platane/snk@v2
        with:
          github_user_name: Ayush1390
          outputs: dist/snake.svg

      # Upload the snake animation as an artifact
      - uses: actions/upload-artifact@v2
        with:
          name: snake
          path: dist/snake.svg

      # Commit and push the generated snake animation back to the repository
      - name: Commit and push snake.svg
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add dist/snake.svg
          git commit -m "Generated snake animation"
          git push
